spring:
  application:
    name: "tastify-backend"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      default-auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: off
server:
  servlet:
    context-path: '/api'
  port: 8080
