spring:
  application:
    name: "recipes"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      default-auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: off
  profiles:
    active: default
server:
  servlet:
    context-path: '/api'
  port: 8080
